version: '3.4'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
    - MYSQL_ROOT_PASSWORD=Sico007_
    - MYSQL_USER=root
    - MYSQL_PASSWORD=Sico007_
    - MYSQL_DATABASE=eqranews
    - MYSQL_TCP_PORT=3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    networks:
      testing_net:
        ipv4_address: 172.28.1.1


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Sico007_
    restart: always
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  eqranews.react.net.spa:
    stdin_open: true
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}eqranewsreactnetspa
    build:
      context: .
      dockerfile: eqranews.react.net.spa/Dockerfile
    environment:
      -  CI=true
      -  MYSQL_HOST=172.28.1.1
      -  MYSQL_ROOT_PASSWORD=Sico007_
      -  MYSQL_USER=root
      -  MYSQL_PASSWORD=Sico007_
      -  MYSQL_DATABASE=eqranews
      -  MYSQL_TCP_PORT=3306
      -  ASPNETCORE_ENVIRONMENT=Development
      -  CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  eqranews.client.mvc:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}eqranewsclientmvc
    build:
      context: .
      dockerfile: eqranews.client.mvc/Dockerfile
    environment:
      MYSQL_HOST: 172.28.1.1
      MYSQL_ROOT_PASSWORD: Sico007_
      MYSQL_USER: root
      MYSQL_PASSWORD: Sico007_
      MYSQL_DATABASE: eqranews
      MYSQL_TCP_PORT: 3306
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      testing_net:
        ipv4_address: 172.28.1.4


volumes:
  dbdata:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

